# Generated by Django 3.2.4 on 2021-06-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_buy_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='mid',
            field=models.ManyToManyField(blank=True, null=True, related_name='patients', to='store.medicine'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='store.patient'),
        ),
    ]
