# Generated by Django 3.2.4 on 2021-06-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210625_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='quantity',
        ),
    ]
