# Generated by Django 3.2.4 on 2021-06-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_buy_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy',
        ),
    ]
