# Generated by Django 3.2.4 on 2021-06-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.FloatField(default=15),
        ),
    ]
