# Generated by Django 3.2.4 on 2021-06-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210626_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='billid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cost', models.FloatField()),
                ('billid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='store.bill')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='store.medicine')),
            ],
        ),
    ]
