# Generated by Django 3.2.4 on 2021-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_bill_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
